name: DABI_2025

services:
  data-db:
    container_name: dabi_postgres
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=data
    expose:
      - 5432

  server:
    container_name: prefect_server
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api #changed from 127.0.0.0:4200/api so dashboard works
      - PREFECT_API_URL=http://127.0.0.1:4200/api 
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://admin:pass123@data-db:5432/data #changed from 'sqlite+aiosqlite:////opt/prefect/prefect.db' so dashboard works
    ports:
      - 4200:4200

  cli:
    container_name: dbt_cli
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - ".:/root/flows"
    environment:
      - PREFECT_API_URL=http://server:4200/api

  worker:
    container_name: prefect_worker
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ["/opt/prefect/start-worker.sh"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: prefect-dbt-network
