dabi_2025:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_PG_HOST', 'localhost') }}"
      user: admin
      password: pass123
      port: 5432
      dbname: data
      schema: example
      connect_timeout: 30
